### ISSUE TITLE
Running it locally?

### ISSUE THREAD

**Issue by antarpreet11** [omcal/codecrafters-git-cpp#1]
Hey sorry to bother you but I was wondering how you ran your code locally. 
I am on step 3 right now and trying to run as follows: 
- Created test dir at root (in codecrafters-git-cpp)
- Then tried running : ../your_git.sh init
- This returns the following error - CMake Error: The source directory does not appear to contain CMakeLists.txt.
- Alternatively if I just place the CMakeLists.txt file inside this test dir, then it shows the error - 
- `CMake Error at /usr/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:130 (message):
  Could not find toolchain file: /scripts/buildsystems/vcpkg.cmake
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!`

Request: Please tell me what steps you took to be able to run this code locally on a freshly cloned repo in windows. I used WSL cli in vscode.

**Comment by omcal** [comment]
Hello,

I was working on the [Codecrafters](https://app.codecrafters.io/catalog) challenge. If you're interested, please check them out—they are awesome.

I made a mistake while uploading, but I believe I have fixed it. It is working on my local Linux machine, and you might have encountered an error due to the Windows environment. Thank you for pointing out the issue.

Have a great day! 😊

**Comment by omcal** [comment]
Also my steps are at ubuntu:

1. Clone The repo
2. mkdir build && cd build
3. cmake ..
4. make
5. Now you can run the see the binary which called "server"
I hope it would help you

**Comment by antarpreet11** [comment]
Thanks a lot, I was following codecrafters but their instructions for locally running this weren't working for me. This helped me a lot. Thank you!
